name: Test nix-on-droid in an emulator
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 1

env:
  NIXPKGS_ALLOW_UNFREE: 1
  NIXPKGS_ACCEPT_ANDROID_SDK_LICENSE: 1

jobs:
  generate-matrix-and-warm-cache:
    name: Generate matrix and warm cache
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up Nix environment
        uses: ./.github/actions/setup-nix-environment

      - name: Extract test matrix from flake
        id: set-matrix
        run: |
          TEST_JSON=$(nix build .#testMatrixJson --no-link --print-out-paths | xargs cat)
          echo "tests=$TEST_JSON" >> "$GITHUB_OUTPUT"

      - name: Build bootstrap zipball
        run: nix build .#bootstrapZip-x86_64

      - name: Archive bootstrap zipball
        uses: actions/upload-artifact@v7.0.1
        with:
          name: bootstrap-x86_64.zip
          path: result/bootstrap-x86_64.zip
          retention-days: 2

      - name: Build and cache all test runners
        run: nix build --impure .#allTestDerivations --no-link

  emulate:
    name: Run tests in emulator
    needs:
      - generate-matrix-and-warm-cache
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        script: ${{ fromJson(needs.generate-matrix-and-warm-cache.outputs.tests) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Set up Nix environment
        uses: ./.github/actions/setup-nix-environment

      - name: Test script=${{ matrix.script }}
        run: |
          nix run --impure .#integrationTest-${{ matrix.script }}

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: screenshots-${{ matrix.script }}-${{ matrix.api-level }}
          path: tests/emulator/screenshots
          if-no-files-found: warn # 'error' or 'ignore' are also available
